name: lock-closed-issue.yml

on: 
  issues:
    types: [closed]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: Dunning-Kruger/lock-issues@v1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
