name: unlock-reopened-issue.yml

on: 
  issues:
    types: [reopened]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: Dunning-Kruger/unlock-issues@v1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
